---
- name: Create Administrator
  postgresql_user:
    name:            "{{ db_admin }}"
    password:        "{{ db_pass }}"
    encrypted:       yes
    state:           present
    role_attr_flags: SUPERUSER,CREATEDB,CREATEROLE,REPLICATION
  become: yes
  become_user: postgres

- name: Require Password Authentication
  lineinfile:
    name: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    regexp: (local\s+all\s+{{ item }}\s+)peer
    line: \1md5
    state: present
    backrefs: yes
  with_items:
    - postgres
    - all
  become: yes
  register: postgres_config

- name: Restart PostgreSQL
  service: name=postgresql state=restarted
  become: yes
  when: postgres_config | changed

- name: Disable Login for postgres User
  postgresql_user:
    name:            postgres
    db:              postgres
    role_attr_flags: NOLOGIN
    login_user:     "{{ db_admin }}"
    login_password: "{{ db_pass }}"
